---
title: "Evaluate the Simulation Results"
author: "Alan Hubbard"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
```{r, echo=F, message=F,warning=F}
library(data.table)
library(dplyr)
library(glmnet)
library(sl3)
library(tmle3)
library(R6)
library(hal9001)
library(cowplot)
library(ggplot2)

rm(list = ls())
source("uhal_Alan.R")
source("SimSynFunctions_Alan.R")
```

## Simulation Code

```{r, eval=F, echo=T, message=F,warning=F}
generate_data_simple <- function(N,Xranges=c(-1,1,-1,1),betaA=c(0,0.1,-0.4),
                                 betaY0=c(0,1,2,-1),betaC=c(1,7/5,5,3),sdy=1){
  # A simple data generating process
  X1 <- runif(N,Xranges[1],Xranges[2])
  X2 <- runif(N,Xranges[3],Xranges[4])
  pi0 <- plogis(betaA[1]+betaA[2]*X1*X2+betaA[3]*X1)
  A <- rbinom(N,1,prob=pi0)
  muY0 <- betaY0[1]+betaY0[2]*X1*X2 + betaY0[3]*X2^2 +betaY0[4]*X1
  CATE <- betaC[1]*X1^2*(X1+betaC[2]) + (betaC[3]*X2/betaC[4])^2
  muY = muY0+A*CATE
  Y <- rnorm(N,sd=sdy,mean= muY)
  return(tibble(X1=X1,X2=X2,A=A,Y=Y))
}
```


## Load data
```{r, echo=F, message=F,warning=F}
load("April7.rdata")
reg.nmes <- c("int","A","X1","X2")
nmes <- c("ave.dat.A","ave.dat.Y","ave.hal.A",
            "ave.hal.Y","ave.sl.A","ave.sl.Y",
            paste0("regest.dat.",reg.nmes),
            paste0("regSE.dat.",reg.nmes),
            paste0("regest.hal.",reg.nmes),
            paste0("regSE.hal.",reg.nmes),
            paste0("regest.sl.",reg.nmes),
            paste0("regSE.sl.",reg.nmes))

colnames(simp.res) <- nmes

tnmes <- c("est.","se.")            
colnames(tmle.res) <- c(paste0(tnmes,"dat"),
                        paste0(tnmes,"hal"),
                        paste0(tnmes,"sl"))
# True values psiP0<-list(P0A=P0A,P0Y=P0Y,true.ATE,coef.work)

```


## Get simple stats var, bias, MSE for proportions and same with coverage for coefficient estimates


```{r, echo=F, message=F,warning=F}
simp.res <- data.frame(simp.res)
marginsA <- simp.res[,c(1,3,5)]
marginsY <- simp.res[,c(2,4,6)]

kp <- c("regest.dat.A","regSE.dat.A","regest.hal.A","regSE.hal.A",
        "regest.sl.A","regSE.sl.A") 

regrA <- simp.res[,kp]

in.CI <- function(x,tru) {
  xL <- x[1]-1.96*x[2]
  xH <- x[1]+1.96*x[2]
  return(tru > xL & tru < xH)
}

bias.var.MSE <- function(x,tru) {
  bias <- mean(x)-tru
  varx <- var(x)
  MSE <- bias^2+varx
  return(c(bias,varx,MSE))
}

res.bias <- apply(marginsA,2,bias.var.MSE,tru=psiP0$P0A)
rownames(res.bias) <- c("bias","var","MSE")
# Re-arrange for plotting
bias.plt <- res.bias[-c(3),]
bias.plt[1,] <- (bias.plt[1,])^2
estim <- c(rep("data",2),rep("hal",2),rep("SL",2))
err <- rep(c("bias2","var"),3)
titl <- paste0("MSE and Squared Bias for 3 Estimators of P(A=1) = ",
               round(psiP0$P0A,2))
plt.bias <- data.frame(Amount=as.vector(bias.plt),estim=estim,err=err)
plt.A <- ggplot(plt.bias, aes(x = estim, y = Amount, fill = err)) +  
  geom_bar(stat = "identity")+ggtitle(titl)


res.biasY <- apply(marginsY,2,bias.var.MSE,tru=psiP0$P0Y)
rownames(res.biasY) <- c("bias","var","MSE")
# Re-arrange for plotting
bias.plt <- res.biasY[-c(3),]
bias.plt[1,] <- (bias.plt[1,])^2
estim <- c(rep("data",2),rep("hal",2),rep("SL",2))
err <- rep(c("bias2","var"),3)
titl <- paste0("MSE and Squared Bias for 3 Estimators of E(Y) = ",
               round(psiP0$P0Y,2))
plt.bias <- data.frame(Amount=as.vector(bias.plt),estim=estim,err=err)
plt.Y <- ggplot(plt.bias, aes(x = estim, y = Amount, fill = err)) +  
  geom_bar(stat = "identity")+ggtitle(titl)

# Regression coefficient on misspecified model for E(Y|A,X1,X2)
regrA.est <- regrA[,c(1,3,5)]
res.bias.coeff <- apply(regrA.est,2,bias.var.MSE,tru=psiP0[[4]][2])
rownames(res.bias.coeff) <- c("bias","var","MSE")

bias.plt <- res.bias.coeff[-c(3),]
bias.plt[1,] <- (bias.plt[1,])^2
estim <- c(rep("data",2),rep("hal",2),rep("SL",2))
err <- rep(c("bias2","var"),3)
titl <- paste0("MSE and Squared Bias for 3 Estimators of A coeff = ",
               round(psiP0[[4]][2],2))
plt.bias <- data.frame(Amount=as.vector(bias.plt),estim=estim,err=err)
plt.regA <- ggplot(plt.bias, aes(x = estim, y = Amount, fill = err)) +  
  geom_bar(stat = "identity")+ggtitle(titl)

# Coverage
covr <- mean(apply(regrA[,1:2],1,in.CI,tru=psiP0[[4]][2]))
covr <- c(covr, mean(apply(regrA[,3:4],1,in.CI,tru=psiP0[[4]][2])))
covr <- c(covr, mean(apply(regrA[,5:6],1,in.CI,tru=psiP0[[4]][2])))

dat.cvr <- data.frame(estim = c("data","hal","SL"),coverage=covr)

cutoff <- data.frame(yintercept=0.95, Lines='95 percent coverage')

plt.cvr <- ggplot(dat.cvr, aes(x = estim, y = coverage)) +  
  geom_bar(stat = "identity")+ggtitle("Coverage of 95% CI for coefficient on A")+ylim(0,1)+
  geom_hline(aes(yintercept=yintercept, linetype=Lines), cutoff,linetype='dashed', color='red')

### tmle results
tmle.est <- tmle.res[,c(1,3,5)]
res.bias.coeff <- apply(tmle.est,2,bias.var.MSE,tru=psiP0[[3]])
rownames(res.bias.coeff) <- c("bias","var","MSE")

bias.plt <- res.bias.coeff[-c(3),]
bias.plt[1,] <- (bias.plt[1,])^2
estim <- c(rep("data",2),rep("hal",2),rep("SL",2))
err <- rep(c("bias2","var"),3)
titl <- paste0("MSE and Squared Bias for 3 Estimators of ATE = ",
               round(psiP0[[3]],2))
plt.bias <- data.frame(Amount=as.vector(bias.plt),estim=estim,err=err)
plt.tmle <- ggplot(plt.bias, aes(x = estim, y = Amount, fill = err)) +  
  geom_bar(stat = "identity")+ggtitle(titl)

# Coverage
covr <- mean(apply(tmle.res[,1:2],1,in.CI,tru=psiP0[[3]]))
covr <- c(covr, mean(apply(tmle.res[,3:4],1,in.CI,tru=psiP0[[3]])))
covr <- c(covr, mean(apply(tmle.res[,5:6],1,in.CI,tru=psiP0[[3]])))

dat.cvr <- data.frame(estim = c("data","hal","SL"),coverage=covr)

cutoff <- data.frame(yintercept=0.95, Lines='95 percent coverage')

plt.cvr.tmle <- ggplot(dat.cvr, aes(x = estim, y = coverage)) +  
  geom_bar(stat = "identity")+ggtitle("Coverage of 95% CI for ATE")+ylim(0,1)+
  geom_hline(aes(yintercept=yintercept, linetype=Lines), cutoff,linetype='dashed', color='red')

```


## Results

```{r, echo=F, message=F,warning=F}
plot_grid(plt.A,plt.Y)
plot_grid(plt.regA,plt.cvr)
plot_grid(plt.tmle,plt.cvr.tmle)


```
